/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as ProtectedIndexRouteImport } from './routes/_protected/index'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as ApiRpcSplatRouteImport } from './routes/api/rpc.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as ProtectedTablesNewIndexRouteImport } from './routes/_protected/tables.new/index'
import { Route as ProtectedTablesTableIdIndexRouteImport } from './routes/_protected/tables.$tableId/index'
import { Route as ProtectedTablesTableIdSettingsRouteImport } from './routes/_protected/tables.$tableId/settings'
import { Route as ProtectedTablesTableIdRowsNewRouteImport } from './routes/_protected/tables.$tableId/rows.new'
import { Route as ProtectedTablesTableIdRowsRowIdRouteImport } from './routes/_protected/tables.$tableId/rows.$rowId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedTablesNewIndexRoute = ProtectedTablesNewIndexRouteImport.update({
  id: '/tables/new/',
  path: '/tables/new/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedTablesTableIdIndexRoute =
  ProtectedTablesTableIdIndexRouteImport.update({
    id: '/tables/$tableId/',
    path: '/tables/$tableId/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedTablesTableIdSettingsRoute =
  ProtectedTablesTableIdSettingsRouteImport.update({
    id: '/tables/$tableId/settings',
    path: '/tables/$tableId/settings',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedTablesTableIdRowsNewRoute =
  ProtectedTablesTableIdRowsNewRouteImport.update({
    id: '/tables/$tableId/rows/new',
    path: '/tables/$tableId/rows/new',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedTablesTableIdRowsRowIdRoute =
  ProtectedTablesTableIdRowsRowIdRouteImport.update({
    id: '/tables/$tableId/rows/$rowId',
    path: '/tables/$tableId/rows/$rowId',
    getParentRoute: () => ProtectedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ProtectedIndexRoute
  '/login': typeof LoginRoute
  '/api/$': typeof ApiSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/tables/$tableId/settings': typeof ProtectedTablesTableIdSettingsRoute
  '/tables/$tableId/': typeof ProtectedTablesTableIdIndexRoute
  '/tables/new/': typeof ProtectedTablesNewIndexRoute
  '/tables/$tableId/rows/$rowId': typeof ProtectedTablesTableIdRowsRowIdRoute
  '/tables/$tableId/rows/new': typeof ProtectedTablesTableIdRowsNewRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/api/$': typeof ApiSplatRoute
  '/': typeof ProtectedIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/tables/$tableId/settings': typeof ProtectedTablesTableIdSettingsRoute
  '/tables/$tableId': typeof ProtectedTablesTableIdIndexRoute
  '/tables/new': typeof ProtectedTablesNewIndexRoute
  '/tables/$tableId/rows/$rowId': typeof ProtectedTablesTableIdRowsRowIdRoute
  '/tables/$tableId/rows/new': typeof ProtectedTablesTableIdRowsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteWithChildren
  '/login': typeof LoginRoute
  '/api/$': typeof ApiSplatRoute
  '/_protected/': typeof ProtectedIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/_protected/tables/$tableId/settings': typeof ProtectedTablesTableIdSettingsRoute
  '/_protected/tables/$tableId/': typeof ProtectedTablesTableIdIndexRoute
  '/_protected/tables/new/': typeof ProtectedTablesNewIndexRoute
  '/_protected/tables/$tableId/rows/$rowId': typeof ProtectedTablesTableIdRowsRowIdRoute
  '/_protected/tables/$tableId/rows/new': typeof ProtectedTablesTableIdRowsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/api/$'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/tables/$tableId/settings'
    | '/tables/$tableId/'
    | '/tables/new/'
    | '/tables/$tableId/rows/$rowId'
    | '/tables/$tableId/rows/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/api/$'
    | '/'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/tables/$tableId/settings'
    | '/tables/$tableId'
    | '/tables/new'
    | '/tables/$tableId/rows/$rowId'
    | '/tables/$tableId/rows/new'
  id:
    | '__root__'
    | '/_protected'
    | '/login'
    | '/api/$'
    | '/_protected/'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/_protected/tables/$tableId/settings'
    | '/_protected/tables/$tableId/'
    | '/_protected/tables/new/'
    | '/_protected/tables/$tableId/rows/$rowId'
    | '/_protected/tables/$tableId/rows/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRoute: typeof ProtectedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiSplatRoute: typeof ApiSplatRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/tables/new/': {
      id: '/_protected/tables/new/'
      path: '/tables/new'
      fullPath: '/tables/new/'
      preLoaderRoute: typeof ProtectedTablesNewIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/tables/$tableId/': {
      id: '/_protected/tables/$tableId/'
      path: '/tables/$tableId'
      fullPath: '/tables/$tableId/'
      preLoaderRoute: typeof ProtectedTablesTableIdIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/tables/$tableId/settings': {
      id: '/_protected/tables/$tableId/settings'
      path: '/tables/$tableId/settings'
      fullPath: '/tables/$tableId/settings'
      preLoaderRoute: typeof ProtectedTablesTableIdSettingsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/tables/$tableId/rows/new': {
      id: '/_protected/tables/$tableId/rows/new'
      path: '/tables/$tableId/rows/new'
      fullPath: '/tables/$tableId/rows/new'
      preLoaderRoute: typeof ProtectedTablesTableIdRowsNewRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/tables/$tableId/rows/$rowId': {
      id: '/_protected/tables/$tableId/rows/$rowId'
      path: '/tables/$tableId/rows/$rowId'
      fullPath: '/tables/$tableId/rows/$rowId'
      preLoaderRoute: typeof ProtectedTablesTableIdRowsRowIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedIndexRoute: typeof ProtectedIndexRoute
  ProtectedTablesTableIdSettingsRoute: typeof ProtectedTablesTableIdSettingsRoute
  ProtectedTablesTableIdIndexRoute: typeof ProtectedTablesTableIdIndexRoute
  ProtectedTablesNewIndexRoute: typeof ProtectedTablesNewIndexRoute
  ProtectedTablesTableIdRowsRowIdRoute: typeof ProtectedTablesTableIdRowsRowIdRoute
  ProtectedTablesTableIdRowsNewRoute: typeof ProtectedTablesTableIdRowsNewRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedIndexRoute: ProtectedIndexRoute,
  ProtectedTablesTableIdSettingsRoute: ProtectedTablesTableIdSettingsRoute,
  ProtectedTablesTableIdIndexRoute: ProtectedTablesTableIdIndexRoute,
  ProtectedTablesNewIndexRoute: ProtectedTablesNewIndexRoute,
  ProtectedTablesTableIdRowsRowIdRoute: ProtectedTablesTableIdRowsRowIdRoute,
  ProtectedTablesTableIdRowsNewRoute: ProtectedTablesTableIdRowsNewRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRoute: ProtectedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiSplatRoute: ApiSplatRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
